#!/bin/bash
# 本地测试演示脚本

echo "============================================"
echo "📚 本地测试演示"
echo "============================================"
echo ""

echo "步骤 1: 配置 OSS 凭证"
echo "----------------------------------------------"
echo "方式 1: 运行配置向导（推荐）"
echo "  ./setup_credentials.sh"
echo ""
echo "方式 2: 手动编辑配置文件"
echo "  cp .env.local.example .env.local"
echo "  vim .env.local  # 填入你的 AccessKey"
echo ""
echo "方式 3: 直接设置环境变量"
echo "  export OSS_ACCESS_KEY_ID='your_key'"
echo "  export OSS_ACCESS_KEY_SECRET='your_secret'"
echo ""

echo "步骤 2: 加载配置"
echo "----------------------------------------------"
echo "  source .env.local"
echo ""

echo "步骤 3: 运行测试"
echo "----------------------------------------------"
echo "测试示例策略（1 只股票，1 天）:"
echo "  python local_test.py example_simple_strategy.py \\"
echo "    --date 20250106 \\"
echo "    --codes \"000001.SZ\""
echo ""
echo "或使用快捷脚本:"
echo "  ./quick_test.sh example_simple_strategy.py 20250106 \"000001.SZ\""
echo ""

echo "步骤 4: 测试你的策略"
echo "----------------------------------------------"
echo "  python local_test.py taq_generator_strategy.py \\"
echo "    --date 20250106 \\"
echo "    --codes \"000001.SZ,000002.SZ\" \\"
echo "    -v"
echo ""

echo "============================================"
echo "💡 提示"
echo "============================================"
echo "- 第一次测试建议只用 1 只股票 1 天（约 2 元流量费）"
echo "- 测试通过后再测试多天或多股票"
echo "- 确认无误后提交到集群（集群内网免费）"
echo ""
echo "详细文档:"
echo "  - 使用指南: docs/LOCAL_TEST_GUIDE.md"
echo "  - 网络配置: docs/NETWORK_CONFIG.md"
echo ""
